apiVersion: v1
kind: ServiceAccount
metadata:
  name: c11-dns-ingress
  labels: {app.kubernetes.io/part-of: c11-callback-ingress}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: c11-https-ingress
  labels: {app.kubernetes.io/part-of: c11-callback-ingress}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: c11-smtp-ingress
  labels: {app.kubernetes.io/part-of: c11-callback-ingress}
automountServiceAccountToken: false
