{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "sccap.fullname" . }}-migrate-{{ .Release.Revision }}
  labels:
    {{- include "sccap.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backoffLimit: {{ .Values.migrations.backoffLimit }}
  template:
    metadata:
      labels:
        {{- include "sccap.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migration
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "sccap.serviceAccountName" . }}
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile: {type: RuntimeDefault}
      containers:
        - name: migrate
          image: {{ include "sccap.apiImage" . }}
          imagePullPolicy: {{ .Values.images.api.pullPolicy }}
          command: ["alembic", "upgrade", "head"]
          workingDir: /app
          envFrom:
            - secretRef:
                name: {{ .Values.runtime.migrationSecret }}
          securityContext:
            {{- include "sccap.securityContext" . | nindent 12 }}
          resources:
            requests: {cpu: 100m, memory: 128Mi}
            limits: {cpu: 500m, memory: 512Mi}
{{- end }}
