"""Status constants for durable per-scan task ledger rows."""

STATUS_SCAN_TASK_PENDING = "pending"
STATUS_SCAN_TASK_RUNNING = "running"
STATUS_SCAN_TASK_COMPLETED = "completed"
STATUS_SCAN_TASK_FAILED = "failed"
STATUS_SCAN_TASK_STALE = "stale"
STATUS_SCAN_TASK_RETRYABLE = "retryable"

TERMINAL_SCAN_TASK_STATUSES = {
    STATUS_SCAN_TASK_COMPLETED,
    STATUS_SCAN_TASK_FAILED,
}

RETRYABLE_SCAN_TASK_STATUSES = {
    STATUS_SCAN_TASK_PENDING,
    STATUS_SCAN_TASK_STALE,
    STATUS_SCAN_TASK_RETRYABLE,
}
